export const SET_HOME_TEAM = 'SET_HOME_TEAM';
export const SET_VISITOR_TEAM = 'SET_VISITOR_TEAM';
export const SET_HOME_CONTROLLER = 'SET_HOME_CONTROLLER';
export const SET_VISITOR_CONTROLLER = 'SET_VISITOR_CONTROLLER';


